### ISSUE TITLE
Error with pkgconfig in 3.6

### ISSUE THREAD

**Issue by adoyle03** [r-lib/pkgconfig#9]
Hi - I get the following message regarding pkgconfig in 3.6.0. Is this a bug or is this a problem with my session?:

> inner_join(younger_pre, younger_pre, by=joining_vars, suffix = c("_pre", "_post"))
Error in get0(oNam, envir = ns) : 
  lazy-load database 'C:/Users/Alicia/Documents/R/win-library/3.6/pkgconfig/R/pkgconfig.rdb' is corrupt
In addition: Warning messages:
1: In get0(oNam, envir = ns) : restarting interrupted promise evaluation
2: In get0(oNam, envir = ns) : internal error -3 in R_decompress1
>

**Comment by gaborcsardi** [comment]
This is an R bug. You need to restart R if you installed a package that was already loaded.

**Comment by adoyle03** [comment]
Ah. Thanks so much. I appreciate it.

Alicia Doyle Lynch, Ph.D.
Lynch Research Associates
Natick, Massachusetts

www.lynchresearchassociates.com
(508) 494-3751
aliciadlynch@gmail.com
